---
name: nixd
description: Nix language server, based on nix libraries
homepage: https://github.com/nix-community/nixd
licenses:
  - LGPL-3.0
languages:
  - Nix
categories:
  - LSP

source:
  id: pkg:github/nix-community/nixd@1.2.3
  build:
    run: "nix build -L .#"

bin:
  nixd: result/bin/nixd
